### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ysh329** [ysh329/ysh329.github.io#1]
2017-07-21
## OpenCL
1. 读程序：HelloWorld
2. 写程序：矩阵相加，矩阵转置（OpenCL实战有相关的案例，同时熟悉NDRange的维度索引）

## Kaggle
invasive
1. 训练模型：先前几个finetune失败的模型接着finetune（caffe转来的模型，没有flatten0而是flatten_0）
2. 提交结果：resnet、resnext模型

## CV
找到用于分割基于resnet block的FCN架构文件

**Comment by ysh329** [comment]
2017-07-22

## OpenCL

写程序：
1. 向量相加
2. 矩阵相加
3. 矩阵转置

OpenCL实战有相关的案例，同时熟悉NDRange的维度索引

## Kaggle

invasive

1. 训练模型：  freeze指定层数做finetune
2. 计算submmission结果：resnet、resnext、squeezenet、caffenet、inception模型

## CV

训练FCN  
1. 根据基于resnet block的FCN架构文件
HaojieCoding/FCN-ResNet50: FCN based on ResNet50
https://github.com/HaojieCoding/FCN-ResNet50

**Comment by ysh329** [comment]
2017-07-31

## OpenCL

- [ ] 编译PerfCLConv和测试
- [ ] 矩阵相加

## Kaggle

### invasive classification
- [ ] freeze指定层做finetune
- [ ] 重写生成submission的部分

### mask car
- [ ] 下载数据
- [ ] 解压查看数据格式、测试训练样本数量
- [ ] 传到服务器上

**Comment by ysh329** [comment]
2017-08-01

## OpenCL

- [x] jing确认安装中的问题
- [ ] 阅读perfclconvolution代码
- [ ] 矩阵相加
- [ ] 矩阵转置

## Kaggle

### iNatural
- [ ] freeze指定层做finetune
- [ ] 观察不同freeze层对结果的影响

### invasive classification
- [ ] freeze指定层做finetune
- [ ] 计算submmission结果：resnet、resnext、squeezenet、caffenet、inception模型

### mask car
- [ ] 传到服务器上
- [ ] 根据基于resnet block的FCN架构文件: HaojieCoding/FCN-ResNet50: FCN based on ResNet50
https://github.com/HaojieCoding/FCN-ResNet50

**Comment by ysh329** [comment]
2017-08-02 Wed

## OpenCL
- [x] 和jing确认了perfclconvolution/examples/cl_convolution.cpp代码中的几个小问题
- [ ] 阅读perfclconvolution/src/runtime/CL/functions/PerfCLConvolution.cpp代码
- [ ] 矩阵相加
- [ ] 矩阵转置

## Kaggle

### iNatural
- [ ] freeze指定层做finetune
- [ ] 观察不同freeze层对结果的影响

### invasive classification
- [ ] freeze指定层做finetune
- [ ] 上传test数据到服务器
- [ ] 用提交的文件正确性来确定类别，即invasive
- [ ] 计算submmission结果：resnet、resnext、squeezenet、caffenet、inception模型

### mask car
- [ ] 根据基于resnet block的FCN架构文件: HaojieCoding/FCN-ResNet50: FCN based on ResNet50
https://github.com/HaojieCoding/FCN-ResNet50

**Comment by ysh329** [comment]
2017-08-03 Thu

## OpenCL
- [ ] 矩阵相加
- [ ] 矩阵乘法
- [ ] 阅读perfclconvolution/src/runtime/CL/functions/PerfCLConvolution.cpp代码
- [ ] 矩阵转置

## Kaggle

### iNatural
- [ ] freeze指定层做finetune: ref: [arsen_test/mx_train.py | ArsenLuca/arsen_test](https://github.com/ArsenLuca/arsen_test/blob/a101c034e453e495849591153c52ce2ebcf334c7/arsen_toolbox/mx_tools/mx_train.py#L23); [fine-tuning and freezing layers · Issue #6223 · apache/incubator-mxnet](https://github.com/apache/incubator-mxnet/issues/6223)
- [ ] 观察不同freeze层对结果的影响

### invasive classification
- [ ] freeze指定层做finetune
- [ ] 继续提交结果：从resnet-50-0018的预测submission开始
- [ ] 计算submmission结果：resnet、resnext、squeezenet、caffenet、inception、vgg模型

### mask car
- [ ] 根据基于resnet block的FCN架构文件: HaojieCoding/FCN-ResNet50: FCN based on ResNet50
https://github.com/HaojieCoding/FCN-ResNet50

**Comment by ysh329** [comment]
2017-08-04 Fri

## OpenCL
- [x] C语言实现矩阵相加，矩阵转置，矩阵乘法，矩阵点乘
- [ ] 跟OpenCL GEMM的教程 [OpenCL matrix-multiplication SGEMM tutorial](https://cnugteren.github.io/tutorial/pages/page1.html)(https://github.com/yuenshome/myGEMM/blob/master/extra/minimal.cpp)
- [ ] debug opencl-101/code/vec-add-simple
- [ ] 阅读perfclconvolution/src/runtime/CL/functions/PerfCLConvolution.cpp代码


## Kaggle

### iNatural
- [x] 跑模型中：resnet-152，跑到了epoch[4]
- [ ] freeze指定层做finetune: ref: [arsen_test/mx_train.py | ArsenLuca/arsen_test](https://github.com/ArsenLuca/arsen_test/blob/a101c034e453e495849591153c52ce2ebcf334c7/arsen_toolbox/mx_tools/mx_train.py#L23); [fine-tuning and freezing layers · Issue #6223 · apache/incubator-mxnet](https://github.com/apache/incubator-mxnet/issues/6223)
- [ ] 观察不同freeze层对结果的影响

### invasive classification
- [ ] freeze指定层做finetune
- [ ] 继续提交结果：从resnet-50-0013提交后最好（就提交到了18，不继续了）
- [ ] 计算submmission结果：squeezenet-v1.0模型的submission

### mask car

* FCN-VGG效果要好于VGG-ResNet
* 做了data-aug效果会很好

- [ ] 根据基于resnet block的FCN架构文件: HaojieCoding/FCN-ResNet50: FCN based on ResNet50
https://github.com/HaojieCoding/FCN-ResNet50

**Comment by ysh329** [comment]
2017-08-05 Sat

## OpenCL
- [ ] 阅读AMD的OpenCL的矩阵乘代码
- [ ] 跟OpenCL GEMM的教程 [OpenCL matrix-multiplication SGEMM tutorial](https://cnugteren.github.io/tutorial/pages/page1.html)(https://github.com/yuenshome/myGEMM/blob/master/extra/minimal.cpp)
- [ ] debug opencl-101/code/vec-add-simple
- [ ] 阅读perfclconvolution/src/runtime/CL/functions/PerfCLConvolution.cpp代码


## Kaggle

### iNatural
- [ ] 继续跑模型中：resnet-152，目前在epoch[4]
- [ ] freeze指定层做finetune: ref: [arsen_test/mx_train.py | ArsenLuca/arsen_test](https://github.com/ArsenLuca/arsen_test/blob/a101c034e453e495849591153c52ce2ebcf334c7/arsen_toolbox/mx_tools/mx_train.py#L23); [fine-tuning and freezing layers · Issue #6223 · apache/incubator-mxnet](https://github.com/apache/incubator-mxnet/issues/6223)
- [ ] 观察不同freeze层对结果的影响

### invasive classification
- [ ] freeze指定层做finetune
- [x] 继续提交结果：从resnext-101，整体结果（0~18 epoch）不好，提交分数在0.97x~0.98x之间
- [x] 计算submmission结果：squeezenet-v1.1模型的submission

### mask car

* FCN-VGG效果要好于VGG-ResNet
* 做了data-aug效果会很好

- [ ] 根据基于resnet block的FCN架构文件: HaojieCoding/FCN-ResNet50: FCN based on ResNet50
https://github.com/HaojieCoding/FCN-ResNet50

**Comment by ysh329** [comment]
2017-08-08 Mon
1. 整理双周简报
2. 给MXNet提了一个关于tensorboard的Pull Request：tensorboard的使用不够友好，需要在common/fit.py里定义对应的输出logs，否则在直接对用户的train_mnist.py文件中就会只有train的curve而没有eval的curve（因为common/fit.py里没定义）

**Comment by ysh329** [comment]
2017-08-09 Wed
昨天完成：
1. 看了AMD OpenCLsample代码：MatrixMultiplication_Kernels.cl该代码实现不带local memory的矩阵乘法；
2. 景让我写矩阵转置的OpenCL代码：目前在A72上写了矩阵相关操作（乘法、点积、转置）的CPU代码和；

今天计划：
1. OpenCL 矩阵转置、矩阵乘法的代码，比较和CPU的性能

**Comment by ysh329** [comment]
2017-08-10 Thu

昨天完成：
1. 实现了OpenCL矩阵转置的代码两种kernel形式。比较了两种实现的性能，发现粗粒度的效果好一些，自己对global_size理解的不好，继续看这方面的东西；

今天计划：
1. 继续完善OpenCL的矩阵转置的测试代码；
2. 测TensorBoard代码正确性，再次commit；

**Comment by ysh329** [comment]
2017-08-11 Fri

昨天完成：
1. 矩阵转置两个kernel的形式，kernel2有bug调好了（在于global_work_siz的设置问题），改成了通过命令行传入参数，测试了两种kernel的性能，发现粗粒度的（ndim=1，global_work_size=M*M）速度快于细粒度的（ndim=2，global_work_size={M, M}）

今天计划：
1. 继续写kernel3，SIMD形式的kernel
2. 在power机器上写Docker file

**Comment by ysh329** [comment]
2017-08-14 Mon

昨天完成：
1. 矩阵转置完成kernel3，写了4x4和8x8的，没有使用向量化，速度不如kernel_v1，global_work_size={max(heightA, widthA, 1, 1)}的，贾老师说可能是因为kernel_v1里有一个for循环，OpenCL编译器自动对带for的进行了优化。
2. Docker安装MXNet在make时候有点问题，关于cudnn。今天在继续搞一下

今天计划：
1. 继续Docker安装MXNet，
2. 矩阵转置使用向量化的方式，如float8，float4这样的形式

**Comment by ysh329** [comment]
2017-08-14 Tue
昨天完成：
1. Docker的MXNet镜像，提交到了hub.docker.com，perfxlab/private仓库；Tensorflow安装需要先安装bazel这个工具，但是没找到ppcle的对应tag（跟着一个教程做的）；
2. float4没写出来，再仔细研究下。halfN和floatN写法都差不多。

今天计划：
1. 继续float4向量化的OpenCL kernel；
2. 继续Tensorflow的安装教程，找找ppcle的bazal的安装包；找找国内比较快的加速器（昨天看了下阿里云似乎可以今天在研究下，另外网易好像也有，也研究下），其实本身hub.docker.com速度感觉还是挺快的。

**Comment by ysh329** [comment]
2017-08-15 Wed

昨天完成：

1. 完成float4向量化的kernel测试结果也正确。但是因为行列优先的问题需要重构部分代码，全部改为行优先；
2. 换了测试的新数据转了mxnet的格式。因为王茜那边硬盘空间有限，所以换了小点的数据，测试的几个模型（VGG-16，VGG-19，AlexNet，ResNet-152）不受影响；
3. 网络问题TensorFlow安装还在继续（JDK）。比方说有时添加apt的repo，timeout，有时候就可以。

今天计划：

1. 重构转置代码为行优先，写规范float4向量化的kernel（顺道改为halfN）；
2. 继续安装tensorflow；找找国内比较快的加速器（昨天看了下阿里云似乎可以今天在研究下，另外网易好像也有，也研究下），其实本身hub.docker.com速度感觉还是挺快的；
3. 跑起来power里的测试代码（测试模型）。

**Comment by ysh329** [comment]
2017-08-17 Thu

昨天完成：
1. power机器
    1.1 MXNet镜像是正确的（注意使用时候加nvidia-docker命令），测试的代码也写好了（训练阶段的处理图像张数，因为和bsize有关，分别设置跑1,2,4,8,16,32,...1024batch size的结果）剩下就是把对应的log输出，另外再检查下数据是否足够，因为发现bsize本身和sample/s有比较大的关系。
    1.2 TensorFlow还在继续安装，bazel有点小问题。
2. 重构代码：还在继续写

**Comment by ysh329** [comment]
2017-08-18 Fri

昨天完成：

1. power机器重新整理数据：还在下载数据，脚本写好了，就等数据了，还有七八个小时就把数据下载完了。数据差不多大小（小于王茜的40G，大于目前的数据量）；
2. 看了tvm的介绍，build中（opencl选上了）。接着看网站的文档（着重看optimize gemm和gpu卷积优化的教程）。要做的是：优化topi里的schedule，拿到一些自动搜tiling参数的脚本，跑resnet和mobilenet pipeline（后者已经打通）。主要任务是优化depthwise和conv2d。

今天计划：

1. 继续下载数据，等待测试power；
2. 看tvm教程

**Comment by ysh329** [comment]
2017-08-21 Mon

昨天完成：
1. 测试完成了power的四个网络（VGG16, VGG19, ResNet-152, AlexNet）。今天把脚本一写，把对应的log中的值捞出来计算下平均，峰值等等；
2. tianqi给了一个交叉编译的链接，照着做一下放到A72上。自己机器上装好了，但是没有gpu（驱动），get_start.py跑出来是跪的；
3. 矩阵转置。写了float4，float8的，速度还是没有粗粒度带for循环的速度快（应该是for被自动优化了）。改成了halfN的， 'half4' (vector of 4 'half' values) requires cl_khr_fp16 extension to be enabled 。

**Comment by ysh329** [comment]
Carvana Image Masking Challenge | Kaggle
https://www.kaggle.com/c/carvana-image-masking-challenge/discussion/38125

**Comment by ysh329** [comment]
2017-08-22 Tue
昨天完成:
1. power测试搞完了。测试代码，测试数据，日志分析脚本。结果已发wangqian；
2. 矩阵转置试了float8、float16的也调试正确了（小bug）。速度有提升（但还是比不上粗粒度的带for循环的，opencl自动优化的），试了halfN结果不对，不能单从kernel里硬强制转换，需要查看文档开CPU支持half，查文档看A72是否支持；写数据的时候挨个存，效率很低，找更优的方式来搞；
3. tvm还在看交叉编译的文档。

**Comment by ysh329** [comment]
2017-08-23 Wed

1. 昨天搞完双周简报；
2. tvm在板子上make runtime完成；
3. 矩阵转置。查看[GCC的文档Using the GNU Compiler Collection (GCC): Half-Precision](https://gcc.gnu.org/onlinedocs/gcc/Half-Precision.html)，以及ARM A72的手册，A72是支持半精度的（half），但是对于GCC来说，这种写法
```
The __fp16 type may only be used as an argument to intrinsics defined in <arm_fp16.h>,
 or as a storage format. 
For purposes of arithmetic and other operations, __fp16 values in C or C++ expressions
 are automatically promoted to float.
```

**Comment by ysh329** [comment]
2017-08-24 Thu

昨天完成：

卡在两个两个问题上
1. Docker安装：A72上重装docker.io，但是service start不起来；
2. A53上试着build runtime，失败：执行`sudo apt-get install -y liblapack*`得到：
```shell
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 liblapack3 : Breaks: liblapack3gf
E: Unable to correct problems, you have held broken packages.
```

执行`python -m numpy`得到
```shell
/usr/bin/python: /usr/local/lib/python2.7/dist-packages/numpy/linalg/lapack_lite.so: undefined symbol: zungqr_; 'numpy' is a package and cannot be directly executed
```

**Comment by ysh329** [comment]
2017-08-25 Fri

昨天完成：
1. Docker不装了（因为Cortex-A72和A53上面的内存都太小），安装Docker CE的话参考官方的文档（对于ARM平台，官方有提供一个convenient script来协助安装，在ARMv7平台试验了可以，但是没有ARMv8平台的，需要build from source）；
2. TVM：
2.1 Cortex-A53 `make runtime` 失败的问题。因为`lapack_lite.so: undefined symbol: zungqr_; 'numpy' is a package and cannot be directly executed`的问题。有关`Numpy`，已经在github发了Issue看官方那边怎么回应；
2.2 仍然在跟CPU GEMM优化教程结合交叉编译。发现一些问题，比方Numpy算的GEMM和通过CPU算的GEMM比较精度，有精度损失，Numpy精度更高一些。
3. OpenCL 矩阵转置 Kernel 编写无进展：
3.1 改变转置过程中还是使用float4类型来操作；
3.2 存数据时候进行批量存（强制转换float4为float）；
3.3 尝试halfN。在CPU端写，再写对应类型的kernel。

**Comment by ysh329** [comment]
2017-09-04 Mon

1. TVM bandwidth。没有写bind，还需要改参考GPU的GEMM的线程分配，教程里有些细节感觉写的不细，踩了一些坑；
2. 双周简报，今天先收集材料吧，感觉这次的内容应该和上次的差不多。

**Comment by ysh329** [comment]
2017-09-13 Wed

1. TVM：
1.1 自己笔记本安装nv驱动。或者重装tvm
1.2 交叉编译的机器上装opencl 的sdk

**Comment by ysh329** [comment]
2017-11-20 Mon
【未完成】
1. 测试检测网络的性能
根据给出的cfg文件发现是darknet框架。尝试找了一20类40张图像并作整理，但是训练了发现因为是检测网络需要检测的annotation数据（检测框的位置信息）。若直接用分类训练数据训练检测模型会因读取annotation标注文件失败而程序报错。
此外，darknet本身的检测数据的标注和常规的不同，需要转换成对应格式，darknet并没有给出具体例子。下载了VOC数据尝试转换成对应格式，这个过程很慢。

【明天计划】
1. 测试检测网络的性能
只要有一个转换成功——知道了darknet的检测标注形式，我就可以随机对40张图像进行检测框的随意标注。就可以训练网络得到权重（今天尝试用自己的40张图像数据训练分类模型，是没有问题的）。

**Comment by ysh329** [comment]
2017-11-21 Tue
【未完成】
1. 测试检测网络的性能
1.1 单张图片训练时间很长。发现代码中设置跑10000次保存结果，改了代码重新编译；
1.2 发现darknet自己实现的gemm，可以调用openblas，但是考虑到比较麻烦还是切换到caffe写prototxt。



【明天计划】
1. 测试检测网络的性能
1.1 写caffe的deploy.prototxt，测试性能

**Comment by ysh329** [comment]
2017-11-22 Wed
【未完成】
1. 测试检测网络的性能
1.1 完成测试openblas单线程和双线程的infer时间。发现在卷积上，双线程比单线程基本上有2倍的加速；
1.2 未完成测试perfblas+perfdnn单线程和双线程的infer时间。之前测过perfblas，对于mxnet需要重新写openblas的前缀的open为perf，并将export perfblas的环境变量。这次测试caffe，需要在Makefile.config中指定perfblas的具体路径，并export对应环境变量，让caffe的二进制文件可以动态链接上.so文件。

**Comment by ysh329** [comment]
2018-3-15 Thu

【JDminiYOLOv2】
1. 先前发现cpu和gpu的结算结果与darknet不一致。因为如下几个问题：
  1.1 网络中的激活函数全部是relu，即x小于0时为0，而该接口没有暴露出来需要改动`./src/backend/backend.c`中的激活函数的系数为0；
  1.2 网络中最后一个激活函数为linear。这点我存疑，因为先前的几个网络在detection之前的最后一个卷积中所用到的激活函数都是linear，但是结果验证是正确的；
  1.3 存在一个reorg层需要将模型转换的结果的层名称，从`Reshape`改为`Reorg`；
  1.4 最后有一个stride=1的pooling，需要特殊处理，即将其pad值改为1，另外对应的函数改为`pooling_yolo`；
  1.5 最诡异的gpu结果（不知道是否解决了）。在修正了以上问题后，cpu的计算结果与darknet在最后一个卷积的结果执行结束基本一致（微弱的精度差异，可以忽略）。但是gpu的结果很奇怪，我从第一层卷积开始与darknet以及inferx-cpu的结果进行验证，发现问题出现在gpu版本的scale层（注：darknet的batchnorm结果，相当于inferxlite的batchnorm+scale的结果，也就是说，验证与darknet的batchnorm的一致性，我需要看inferxlite的scale的结果，另外，我验证了inferxlite的cpu和gpu在batchnorm层的结果是一样的，进一步证明了scale层不同）。然而该gpu-scale层实现是在PerfDNN_CL项目下，InferXLite只是调用PerfDNN_CL的动态链接库文件，且我没有重新编译过，后来我又重新实验，竟然神奇的正确了。我很费解。下面是当时inferxlite的conv0-scale层feature map的截图：
![image](https://user-images.githubusercontent.com/7320657/37450732-1366825a-286a-11e8-9e2e-594ae368130b.png)
总之诡异的结果：
     1.5.1 一开始我认为是编译选项或者Makefile里有问题，比方猜想是否是因为gpu和cpu的编译选项都开了，导致scale操作做了两遍，因为scale操作就是乘以一个系数，但是后来看了`./src/backend/backend.c`源码发现scale层里做了device的判断所以不是。
     1.5.2 另外，gpu和cpu的操作的变量也不一样，换句话说，即使处理两遍，变量名也不同。
     1.5.3 另外，有考虑是否是同步异步的缘故，可能是异步的原因（非阻塞）导致有些结果没有计算，有些算完了提前结束了。但是查看了PerfDNN_CL库，发现是同步的（download数据部分），也检查了InferXLite在获取OpenCL数据的时候也是同步的，所以这个原因也被排除了，另一个可能是在`./sample/app.c`的`clFinish`函数没有执行，当然或许是这个原因吧，但是我之前跑YOLOtinyvoc等YOLOv2也都是好的正常的，这就奇怪了。

2. InferXLite在cpu和gpu的精度上有差异。现在这个gpu诡异的问题不出现了，也验证了gpu和cpu对于第一个卷积和池化的计算结果是一致的。目前cpu到最后一个卷积的计算结果和darknet是一致的，但是gpu的有很大的计算精度差异，差异大小是x+-x这种。我认为导致差异的可能在以下几个地方，需要进一步检查：
  2.1 reorg层操作，检查reorg层前后的feature map结果
  2.2 route层操作，检查两路分支合并前后的feature map结果
  2.3 pool_yolo层操作，检查特殊的stride=1的池化层（即最后一个池化）前后的feature map结果

3. InferXLite下的模型转化工具darknet
  3.1 对reorg层转换有问题，名称仍旧为reshape，需要自动改为reorg
  3.2 对特殊的stride=1的池化层转换有问题
    3.2.1 接口名从`inferx_pooling`改为`inferx_pooling_yolo`
    3.2.2 接口的右和下的pad值从`0`改为`1`

**Comment by ysh329** [comment]
2.1 reorg层操作，检查reorg层前后的feature map结果，未检验
2.2 route层操作，检查两路分支合并前后的feature map结果，cpu与gpu结果一致，与darknet精度有一定可接受的损失，正确
2.3 pool_yolo层操作，检查特殊的stride=1的池化层（即最后一个池化）前后的feature map结果

**Comment by ysh329** [comment]
后来仔细对比（写了个一个脚本比较）发现其实conv17的输入就不对，人眼抽查的时候的确没发现cpu与gpu的不同，看来还是不能拍脑袋。要拿数据所有对比过的结果来验证，而不是抽验。**好在对比的时候我们以channels为单位，就以`height * width`的值为间隔来看，果然发现了不同（之前我抽检发现是正确的，也只是我抽检的地方）**。

发现问题处在reorg层，cpu与gpu不同，似乎是因为形状的缘故，先前在跑YOLOv2时是正方形的输入，如288或者352的，这次是矩形的，可能是reorg的gpu版本在处理矩形有问题（可能是某个小变量名写错了，比方列数写成了行数，或者反之等等），还需要进一步查看。

**Comment by ysh329** [comment]
再次检查，权重与输入是一致的

**Comment by ysh329** [comment]
# 财务报表入门

对于一家公司而言，最核心重要的就是财务报表，可以通过财务报销的结果，推测其商业逻辑，进而明白公司价值和选择投资方向。

## 财务报表三个组成

财务报表是基于会计信息制作出来的。会计信息是为信息使用者提供有用信息的使用系统，会计信息分为三部分。

1. 资产负债表，其最重要的等式是，资产，等于，负债，加上，所有者的权益；
2. 利润表。收入，减，费用，等于利润。以上两个等式构成了它们二者表的结构；
3. 现金流量表。包含经营性现金流，投资性现金流和筹资性现金流。

## 会计与财务的职责

有许多人对会计和财务有误解，以为是一样的，然而二者不同，因为两者整体的工作职责不同。

会计最重要的是工作职责是记账，算账，报账。用专业术语来说就是确认，计量和报告。

- 第一是记账，即确认。若公司发生经济业务，这个业务是否能进入会计报表里，如果能，那要考虑要计算多少，首先要确认这个经济事项是否记为会计信息，然后再确定金额以及账务；
- 第二是算账，算账实际上是计量的问题。比方公司买入固定资产500万元，500万元的设备，按照五年的时间来摊销，根据平均年限法可以算出平均每年摊销额度是一百万元，这是计量的概念；
- 第三是报账，报账就是提交财务报表，最后能把财务报表制作完成，并写成报告。

而财务的职责不一样，其最重要的是三个职责：

- 第一是筹资，能够从市场或债券人获取现金支持；
- 第二是投资，如何分配资源，考虑投资到什么项目上；
- 第三是分配，投资完成后可能有收益，今明也有可能带来收入，怎么来分配？按什么现金鼓励方案，这就是财务的工作。

## 三大财务报表体现了什么？

- 利润表体现公司的获利能力，以效益为基础。一般来说，一家公司操纵了利润，操纵利润体现了他的能力不足，若能力不足，就更需要更好的利润，进而弥补能力不足表现的无能，一家公司的利润表现出来的是其能力。
- 现金流量表其实体现了一家公司的活力，拥有良好的现金流，是公司保持活力，想干什么就能干什么的基础，如果公司确实有利润，但是没有现金流，那什么也干不了，即使有应收账款，但也没有用。
- 资产负债表，体现是公司的实力，而且资产负债表比后面两个表中重要，因为即使没有后面两个表，也可以通过该表计算出来。如果没有资产负债表，就表现不出公司的核心。

## 看财务报表的方式

所以从看财务报表的角度来看，第一从资产负债表进行入手，再去分析利润表和现金流量表，这三个表是联合起来分析。可以看出：  

1. 公司是否能得到利润；
2. 能否得到收益；
3. 市场效益如何。
